Fix HTTP upload
profanity-im/profanity pull request #1500
Opened 2021-03-10 16:32 UTC by mwuttke97

This should hopefully fix #1499.

2021-03-10 16:52 UTC, jubalh commented on src/tools/http_upload.c
> +    if (auth_header) {
free(NULL) is a noop. So no need for `if`

2021-03-10 17:13 UTC, jubalh commented
```
Fix string STANZA_NS_HTTP_UPLOAD
":0" was missing at the end.
```
is an inappropriate description for the first commit.

In version 0.1.1 of XEP-0363 the namespace was just `urn:xmpp:http:upload namespace`. Only in a later version `urn:xmpp:http:upload:0` was introduced.

Regarding the second commit it seems that 0.5.0 of XEP-0363 allowed for these headers.

I would like to change the description to reflect what is actually changed. "Fix" sounds like something was broken. But it's more like adhering/updating to the newer version.

2021-03-10 17:15 UTC, jubalh commented
It's very good that you found this. In https://profanity-im.github.io/xeps.html we claim to support the latest version. Obviously we didn't. Until your PR ;)

2021-03-10 17:48 UTC, jubalh commented
So it seems to really support the namespace bump to `:0` then we need to change more in the stanza.

2021-03-11 11:05 UTC, mwuttke97 commented
Thanks for all the feedback! Indeed, I didn't notice that the XEP actually was updated. I will implement the corresponding updates.

2021-03-11 11:08 UTC, mdosch commented
I experimented a little bit (without C, libstrophe or profanity code 
knowledge) and got to a point where profanity sends a (hopefully) valid 
stanza and gets a slot. But I don't know yet how to parse the reply in 
iq.c.

On 11.03.2021 03:05, Maximilian Wuttke wrote:
>Thanks for all the feedback! Indeed, I didn't notice that the XEP actually was updated. I will implement the corresponding updates.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/profanity-im/profanity/pull/1500#issuecomment-796655722

2021-03-11 15:32 UTC, jubalh requested changes
Usually in git people use something like `Co-authored-by: name <name@domain.org>` for a commit that has more than one author :)

2021-03-11 16:15 UTC, mwuttke97 commented
Do you know why the CI fails?

2021-03-11 16:22 UTC, jubalh commented on src/tools/http_upload.c
> +
maybe one line too much :)

2021-03-11 16:27 UTC, jubalh commented
> Do you know why the CI fails?

No idea. Annoying.. Maybe python2 vs 3..

2021-03-11 16:34 UTC, jubalh approved these changes
Looks good. Except the one empty line too much. But doesnt' matter much :)

2021-03-11 16:35 UTC, merged