Restart OMEMO Session after lost connection
profanity-im/profanity pull request #1549
Opened 2021-06-01 17:16 UTC by DebXWoody

When the connection has been re-established, chat and groupchat with OMEMO
should restat the OMEMO Session.

Fix: #1530

2021-06-01 17:18 UTC, DebXWoody commented
Just implemented, didn't test the changes.

2021-06-01 17:38 UTC, DebXWoody commented
My first tests was fine - I guess.
@mdosch feel free to test.

2021-06-01 20:45 UTC, jubalh requested changes
`if ( mucwin->is_omemo ) {` follows not the coding style. Maybe try to run clang format :)
In case you change this, could you also squash the commits together? `git rebase -i HEAD~2` (number depends) and then only have one commit with the message of your currently first commit. Since the other two commits are more like for completion of the actual task :)

2021-06-02 09:39 UTC, mwuttke97 approved these changes
Looks good to me and also works for me. No more warning/error after reconnection.

2021-06-02 11:07 UTC, jubalh approved these changes

2021-06-02 11:22 UTC, merged