Show return symbol for embedded newlines
profanity-im/profanity pull request #1690
Opened 2022-04-11 10:59 UTC by paulfertser

When editing multi-line messages or comments everything past the first
newline becomes invisible.

This patch fixes it by substituting a Unicode symbol for "return"
instead of printing the newline as is. On locales where it's not
available single backslash is used instead.

2022-04-11 11:31 UTC, jubalh commented
Good idea!

When using `/editor` I don't see this. Is it possible to add it there as well?

And just some minor point:
Do we also want this symbol in the following case?
![Screenshot from 2022-04-11 13-29-25](https://user-images.githubusercontent.com/1658215/162730712-5ebc2cdb-cb05-4f09-9894-ff2278e6e704.png)

2022-04-11 19:33 UTC, jubalh requested changes
Please fix tests/style.
And would be great if we could fix `/editor` to work as well.

2022-04-12 09:14 UTC, paulfertser commented
Odd github doesn't let me see it. Am I supposed to be logged in or something?
I'll work on fixing the warning another way, thank you.

2022-04-12 09:23 UTC, jubalh commented
It works fine for me with a browser where I'm not logged in.

2022-04-12 10:09 UTC, jubalh approved these changes

2022-04-12 10:09 UTC, merged

2022-04-12 10:09 UTC, jubalh commented
Thanks!