Fix duplicate messages in chat with oneself.
profanity-im/profanity pull request #1717
Opened 2022-05-29 13:58 UTC by MarcoPolo-PasTonMolo

Messages would get duplicated when you chat with yourself, worse if you
had omemo enabled the duplicated message would say something along the
lines of "Your client doesn't support OMEMO". The cause was carbons
when the message was sent from another client, whilst it was a sent
and received message when profanity was the one to send it. This commit
ignores the carbon message in the 1st case and ignores the received one
in the 2nd.

Fixes https://github.com/profanity-im/profanity/issues/1595

2022-05-30 16:09 UTC, jubalh commented
> Messages would get duplicated when you chat with yourself

What do you mean by that?

i write to myself in Profanity
I get the message once printed via outgoing
and once via incoming.

So that works.

I now tested to be online with Profanity and Dino. and writing to myself. Same as above happens.

I think that's what's expected?

2022-05-30 17:59 UTC, MarcoPolo-PasTonMolo commented
> I get the message once printed via outgoing
> and once via incoming.
we don't want that, each message should be printed once, if we use omemo the second message is always encrypted

> I tried your PR and I see no difference:
huh, weird. Could you send me the message stanzas you get in xml console when sending from profanity and another client?

2022-05-30 18:11 UTC, jubalh commented
> we don't want that

actually i think people expect that when they write to themsleves that they will see it 2 times (if writing from the same client). like some test about the connection. no?
Anybody knows how it looks like in other clients? Always when I did this I got the message twice?

2022-05-30 18:16 UTC, MarcoPolo-PasTonMolo commented
Yeah you are right. Some messaging app show the response some don't (for the same client). Most xmpp clients seem to not show it, for profanity I think we should also go with that approach since the second message is unencryptable if using OMEMO. Or we should at least find a way to unencrypt it first (I think someone said there's some limitation where clients can't encrypt for themselves?).
Does this pr work for you jubalh?

2022-05-30 18:26 UTC, jubalh commented
>  Does this pr work for you jubalh?

It does. But I feel like maybe I'm missing something.
Need to think a little about it (and didn't review the code yet), thinking about some sideeffects etc.
Or maybe other people (client devs?) can weigh in.

2022-05-31 07:19 UTC, jubalh commented on src/xmpp/message.c
> +        if (msg_stanza && g_strcmp0(xmpp_stanza_get_from(msg_stanza), xmpp_conn_get_jid(conn)) == 0) {
This will prevent all further parsing of the stanza. Including `_handle_chat_states`

2022-05-31 07:19 UTC, jubalh commented
I did a quick test. Without OMEMO.

And when I sent a message to myself (from Profanity) and had receipts on I never got the indication (color change) that the message was received.

2022-05-31 07:20 UTC, jubalh commented
I'm really not sure if we want to throw away all stanzas that come from us. I'm not sure about all the possible use cases and XEPs. But it sounds a little risky to me.

Not displaying them might be another case. But I think we should probably process them anyways.
Still quite unsure about the overall effect of this change.

2022-05-31 11:29 UTC, MarcoPolo-PasTonMolo commented
I moved the check to where the messages get printed on screen.

2022-05-31 12:21 UTC, jubalh commented
That's much better I think.
I tested this with both unencrypted and OMEMO enabled. Works as expected. Just prints the messages one time. No OMEMO errors (like in above mentioned issue).
Only one nitpick left!

2022-05-31 12:22 UTC, jubalh requested changes

2022-05-31 12:22 UTC, jubalh commented on src/ui/window.c
> +            if (g_strcmp0(message->from_jid->fulljid, xmpp_conn_get_jid(connection_get_conn())) != 0) {
Please use `const char* connection_get_fulljid();` instead

2022-05-31 12:51 UTC, MarcoPolo-PasTonMolo commented on src/ui/window.c
> +            if (g_strcmp0(message->from_jid->fulljid, xmpp_conn_get_jid(connection_get_conn())) != 0) {
Done

2022-05-31 13:00 UTC, sjaeckel commented
IMO this patch should not be applied.

If it gets applied it should be hidden behind an option that is disabled by default.

2022-06-07 07:56 UTC, jubalh commented
Okay, let's do that for now.

Maybe over time we will get some feedback from users about this and then can still decide to remove the option or switch the default behaviour.

2022-06-10 21:52 UTC, jubalh commented
I have thought more about this and actually think the new behaviour is better. And that I just was too used to the old one.
I guess it is more modern/user friendly.

I then talked with @weiss about this and he agrees that it's a good behaviour.
He also mentioned that Conversations is doing the same.

So i think we should merge this as is (still not entirely sure if I miss something).
Or did you already start with implementing the preference @MarcoPolo-PasTonMolo ?

2022-06-11 09:32 UTC, MarcoPolo-PasTonMolo commented
> Or did you already start with implementing the preference @MarcoPolo-PasTonMolo ?
No

2022-06-11 10:33 UTC, jubalh approved these changes

2022-06-11 10:33 UTC, merged

2022-06-11 10:34 UTC, jubalh commented
Thanks for your contribution (and patience ;)) !