Add some necessary changes
profanity-im/profanity pull request #1765
Opened 2022-10-09 20:06 UTC by ragu-1997

2022-10-11 14:02 UTC, jubalh commented
I saw now that you edited the text here on the GitHub comment.

Please squash all commits together into one and add the explanation there as well. Like mentioned in the contributing.md. 

About your comments:
i don't see what you mean about `rm -rf` you don't change anything in this regard.

Also i think you didn't explain the nohup and wget changes.

2022-10-16 15:07 UTC, sjaeckel requested changes
The three `exit 0` are borderline nonsense, I'd say they are even harmful.

The default shell behavior is that the exit code of a shell script is equal to the exit code of the last executed process/command. Those changes make these scripts simply always succeed, whereas before their exit code was appropriately the exit code of the thing that should be done.

2022-10-16 15:07 UTC, sjaeckel commented on .builds/openbsd.yml
> +  - nohup
Where is this file even used?

If you change it, make it used in CI, otherwise simply remove it IMO

2022-10-16 15:45 UTC, closed without merging

2022-10-16 15:45 UTC, ragu-1997 commented
Sorry for the misunderstanding Thanks for your explanation sir