Improvements
profanity-im/profanity pull request #1799
Opened 2023-03-17 23:01 UTC by jubalh

Quick "reminder" PR which I will do more in later.
glib 2.76 seems to have some changes regarding g_string_free. Will check in more detail later.

Often our code that uses g_string should be moved to another method anyways. Will also check this later.

2023-03-17 23:10 UTC, jubalh commented
`g_string_free()` change actually was in glib 2.75.3 in following MRs:
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3219
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3226

2023-03-20 16:43 UTC, jubalh commented on src/common.c
> +        return g_strdup_printf("%s", path);
Hm I fail to see what I'm missing right now. exp_path is empty in this case isnt it.

2023-03-20 16:47 UTC, jubalh commented on src/ui/confwin.c
> +    return g_strdup_printf("%s", title);
oops!

2023-03-20 17:20 UTC, sjaeckel requested changes

2023-03-20 17:20 UTC, sjaeckel commented on src/ui/confwin.c
> +    return result;
```suggestion
    return win_get_title((ProfWin*)confwin);
```
Why first dup the result or `win_get_title()`, then free the source and return the dup? Simply return what is returned by `win_get_title()` or not?

Also I've just realized that `win_get_title()` can return `NULL`, maybe make it return an empty string on error?

2023-03-21 14:39 UTC, sjaeckel commented on src/ui/confwin.c
> +    return result;
The reason why I mention it is that the return value of `win_get_title()` is possibly `NULL` and will directly be used e.g. here

https://github.com/profanity-im/profanity/blob/e5e8ff221a08939b43edf488fa2a3b8fe95169ea/src/ui/titlebar.c#L198-L201

1. How does `mvwprintw()` handle a potential `NULL` pointer?
2. I'm pretty sure that most `strlen()` implementations will not take it well :grimacing: 

Just to make it clear: this isn't caused by this change, but was already before like that. I only discovered it while looking at your PR.

I couldn't find a case where the `NULL` was really tested for to decide on behavior, so maybe the best solution would be to also return `strdup(CONS_WIN_TITLE)` in the fall-through case? or maybe even `g_strdup_printf("Error: Window title for type %d unknown", window->type)` to make it clear that something went wrong?

2023-03-22 14:53 UTC, merged