add `/statusbar tabmode irssi`
profanity-im/profanity pull request #1813
Opened 2023-04-03 16:54 UTC by sjaeckel

The existing way how active tabs are displayed didn't allow showing more than 10 tabs. This patch adds a mode where the statusbar shows a comma-separated list of tabs which were active since the last time viewed. This view is inspired by how `irssi` shows the active tabs.

2023-04-04 14:05 UTC, jubalh requested changes
(just commenting to have a better overview)
`/statusbar tabmode default|actlist` as discussed privately.

2023-04-05 07:16 UTC, sjaeckel commented
> (just commenting to have a better overview) `/statusbar tabmode default|actlist` as discussed privately.

I'll wait until #1817 is merged, since that PR touches some of the same parts of the code.

2023-04-08 16:50 UTC, jubalh approved these changes

2023-04-08 16:50 UTC, merged

2023-04-08 16:51 UTC, jubalh commented
Thanks!