JID Display in Titlebar and Fix
profanity-im/profanity pull request #1817
Opened 2023-04-04 00:40 UTC by H3rnand3zzz

See commit messages.
**Note:** on all of the screenshots setting `/statusbar self` set to `off` to preserve privacy of testing account.
## Before
### `/statusbar chat jid`
![image](https://user-images.githubusercontent.com/129467592/229655744-475b74d5-2790-4e17-931e-63986f1bd3f8.png)
### `/statusbar chat user`
![image](https://user-images.githubusercontent.com/129467592/229655744-475b74d5-2790-4e17-931e-63986f1bd3f8.png)

## After
### `/statusbar chat jid`
![image](https://user-images.githubusercontent.com/129467592/229656339-892c0d3b-3663-450d-9221-092992bc5fc2.png)

### `/statusbar chat user`
![image](https://user-images.githubusercontent.com/129467592/229656174-a89b8fc5-748e-479f-94d1-0bfe5d535f7e.png)

2023-04-04 13:33 UTC, jubalh requested changes
The code looks good.
But somehow I'm not too happy with the commit messages.


For example if I go through code later, and do git blame on a certain line and want to see why/what was changed here, it would be more helpful to have a good description that I can quickly read instead of trying to analyze the code in the commit. Because when doing this for many commits it can be quite time intensive. So it would be nice to have more explanatory commit messages.

For example `- Fixes statusbar tabs by respecting "/statusbar chat" setting.` I would like to see what is actually wrong with the current way. what did it look like/behaved and why did you change this.

Sometimes also we want to change something, have some idea in our head but introduce a mistake in the code. And if we describe our actual idea better in the commit message then a reviewer can also better see if the code actually does what the coder wanted it to do.

2023-04-04 14:06 UTC, H3rnand3zzz commented
> The code looks good. But somehow I'm not too happy with the commit messages.
> 
> For example if I go through code later, and do git blame on a certain line and want to see why/what was changed here, it would be more helpful to have a good description that I can quickly read instead of trying to analyze the code in the commit. Because when doing this for many commits it can be quite time intensive. So it would be nice to have more explanatory commit messages.
> 
> For example `- Fixes statusbar tabs by respecting "/statusbar chat" setting.` I would like to see what is actually wrong with the current way. what did it look like/behaved and why did you change this.
> 
> Sometimes also we want to change something, have some idea in our head but introduce a mistake in the code. And if we describe our actual idea better in the commit message then a reviewer can also better see if the code actually does what the coder wanted it to do.

Changed it. I hope that this time it's better

2023-04-07 08:30 UTC, H3rnand3zzz commented
@jubalh please, review. Changes in the description are made as requested, no problems with the code were mentioned.

2023-04-08 16:14 UTC, jubalh requested changes
First commit is wrong.
We have `/titlebar show name|jid`, which so far seems to apply only for MUCs. You need to query this setting and use it to let the user enabling/disabling the nickname and/or jid. It should be possible to turn on BOTH.

2023-04-09 15:49 UTC, jubalh approved these changes

2023-04-09 15:50 UTC, jubalh commented
Looks good! And I also noticed that you improved the commit messages A LOT! Thanks for this. Now the commit messages are much more helpful in quickly understanding the change!

2023-04-09 16:11 UTC, jubalh commented
Now we have a conflict because in the meantime we merged https://github.com/profanity-im/profanity/pull/1813 (sorry about that) which touched the same parts of the code.
You will have to use `git rebase master` on your branch and then need to return `pos`. Do you know how to do that or should we do this for you?

2023-04-09 18:51 UTC, jubalh commented
I noticed something:

What I tried:
* `/statusbar show name` (I have this off by default
* `/msg someone` where I chose someone in my roster that has a nick assigned
* `/statusbar chat jid`
I do this while I'm on the console window. And nothing changes. Only when I go to the window where I wrote to the user it updates it from 'nickname' to his jid.
So it seems I need to cycle all windows where this applies, to make the change actually visible.

2023-04-10 11:41 UTC, H3rnand3zzz commented
I will submit fixed version with the update issue mentioned in a couple of hours.

2023-04-10 18:21 UTC, merged

2023-04-10 18:25 UTC, jubalh commented
Also see e3820d7037a63ff3e09ed84f518dfb7b67f3982f for the info message.

2023-04-10 18:25 UTC, jubalh commented
Thanks @H3rnand3zzz !