Mouse scroll
profanity-im/profanity pull request #1824
Opened 2023-04-13 11:06 UTC by H3rnand3zzz

Added mouse scroll support with shift+scroll using readline.

2023-04-13 11:14 UTC, H3rnand3zzz commented on src/ui/inputwin.c
> +    return g_unichar_isprint(unichar) && (ch != KEY_MOUSE);
should be removed

2023-04-13 15:05 UTC, sjaeckel commented on src/ui/inputwin.c
> +    cons_show(g_strdup_printf("scroll. count: %d, key: %d, %c", count, key, key));
I guess this in only a debug statement, which will go soonish.

FYI `cons_show()` behaves like `printf()`, i.e. you can drop the call to `g_strdup_printf()`. (also you're leaking the value returned :D)

2023-04-18 21:58 UTC, H3rnand3zzz commented
It's ready for review, but not ready for release. I would appreciate advises on lag issue. Probably core-related. Even without binding, mouse scrolling makes considerable lag.

2023-04-19 16:00 UTC, jubalh requested changes

2023-04-19 16:00 UTC, jubalh commented on src/ui/inputwin.c
> +    if (key == 'B') { // mouse wheel down
here i agree with clang that the comments should be on top or inside ;)

2023-04-19 16:00 UTC, jubalh commented on src/command/cmd_defs.c
> +    //
?

2023-04-21 16:16 UTC, sjaeckel requested changes
Again clean and easy to follow.

I'd like to have a second look tomorrow after those proposed changes are included.

2023-04-21 16:16 UTC, sjaeckel commented on src/command/cmd_defs.c
> +    //
```suggestion
```

2023-04-21 16:16 UTC, sjaeckel commented on src/ui/inputwin.c
> +        return 0;
```suggestion
```
This can go, since this function will only be called if this flag is set to true.

2023-05-04 17:52 UTC, H3rnand3zzz commented
To make it clear

At the current stage, the commit is incompatible with mouse and works only with touch pad. I hope to resolve it as soon as possible.

2023-11-13 11:43 UTC, H3rnand3zzz commented
Rebased on master
Followed by changing for alt+up/down instead of shift+up/down. Alt it more intuitive (since it presumes ALTernative behaviour for the same button) and minor changes to merge with previous updates.

2023-11-17 09:42 UTC, jubalh approved these changes

2023-11-22 08:55 UTC, H3rnand3zzz commented
@sjaeckel, is PR ok now?

2023-11-22 09:06 UTC, sjaeckel commented
I'll have a look soon, currently only on mobile

2023-11-28 14:07 UTC, H3rnand3zzz commented
### New revision
 - Changes requested by @sjaeckel are implemented:
   - Removed preference (since alt+arrows support for navigation does not need to be optional)
   - Details are added in command description regarding other terminals' support

2023-12-05 09:57 UTC, sjaeckel approved these changes

2023-12-05 11:25 UTC, merged