`auto_char` cleanup
profanity-im/profanity pull request #1858
Opened 2023-06-15 16:36 UTC by H3rnand3zzz

See commit messages

2023-06-29 08:18 UTC, sjaeckel commented
I really like how this is evolving!

Just as a heads up: IMO this PR gets too huge and must be split up into multiple ones. But only when you're finished and I guess the best would be 1 PR per commit as they're already separating the topics. (Minus the fixup commit(s) which should be squashed into the appropriate topic ones). 👍
... But maybe I'm also telling you what you had already planned to do 😆

2023-07-04 16:32 UTC, H3rnand3zzz commented
Since it's going to be split up, I will keep it "drafted" and then close/something. Please, don't review this one.

2023-07-05 09:25 UTC, jubalh commented
I'm not quite certain what's the plan here.
But if this is going to be split then the most important part should be this:

A commit should do one thing. For example:
```
[Cleanup prefs_get_string](https://github.com/profanity-im/profanity/pull/1858/commits/b57d9a5ef022cb4c2d39cb550a27610ecbbeac7c)

Improve usage of `gchar` and `char` by setting them correctly
Increase usage of `auto_gchar` and `auto_char`
Fix 2 mem leaks (rosterwin.c, avatar.c)
Improve documentation
```

is doing a lot of unrelated things. And I don't quite see why they are in one commit. This makes it hard to review. To pick and choose changes.


Similar for:

```
[Big cleanup char to auto_char](https://github.com/profanity-im/profanity/pull/1858/commits/5207b275e180dcd194aea813540396f90c965b51)

Replace `gchar` and `g_free` to `auto_gchar`
Improve readability
Improve documentation for certain functions to increase transparency
Correct certain  `char` functions/variables to `gchar`
Fix most of the cases for 1819 issue
```

I think you need a commit
* to change char to auto_char
* fix memleaks (if unrelated to the other commit)
* change jid to auto_jid
* improve documentation
* change g_strfreev() to auto_gcharv

something like this. I'm not sure if i missed something because really its hard to read :)

And for me it would be okay if such commits would be in one cleanup PR. But sure if this touches too many lines/code then it can also help to split it to several PRs. What I mean is that the one atomic change per commit is the more important splitting.

2023-07-05 09:31 UTC, jubalh commented
For example in https://github.com/profanity-im/profanity/pull/1863 you now have only one commit. But you do 2 things there:
* Improve the documentation and change the variable name of a function
* Change from char to auto_char to automatically free it.

These things are not related and should be separate commits.

2023-07-12 11:53 UTC, jubalh commented
Your other PR got merged. First commit can be dropped I guess.
Then the rest cleaned up. You dont need a new PR for this. I will review here. It shouldnt be too many lines left after the chat->autochar change.

2023-07-12 14:10 UTC, jubalh requested changes
Again please dont mix in one commit several things that dont belong together.

Split out the change int he first (two?) commits.

And put the description of the functions above the functions in the .c file.
Also please be aware that we decided in https://github.com/profanity-im/profanity/issues/1859 that we don't want doxygen comments.

So far I accepted them in cases where I believed that our function name is really not descriptive enough and your comments were a good explanation.
I would still prefer them written in another way but its also fine by me to have them like this. But the goal will not be to have doxygen comments for each function.

2023-07-12 14:10 UTC, jubalh commented on src/config/files.c
> - */
Comment about function should be in the .c file and not the header.
The dev is reading the .c file and shouldnt have to switch to the header just to read the comment.
Maybe some IDEs take it from the .h file but I'm not a fan of this.
True for all other cases in this commit as well.

And please break up this commit. The docu change should be a commit of its own. And not mixed with the char one.

2023-07-13 19:18 UTC, H3rnand3zzz commented
> Looks good! But there are still function description comments in one .h file :)

it was for macros, since they are used only in .h file

2023-07-14 05:22 UTC, jubalh approved these changes
Huge PR to review. I hope I didn't miss anything. LGTM.

2023-07-14 05:22 UTC, jubalh commented on src/config/preferences.c
> +prefs_set_string(preference_t pref, gchar* new_value)
I think `value` was quite descriptive ;)

2023-07-14 05:22 UTC, jubalh commented on src/config/preferences.c
> -prefs_get_string_with_option(preference_t pref, gchar* option)
It looks like we even don't use this function anymore?

2023-07-14 05:23 UTC, jubalh commented
> it was for macros, since they are used only in .h file

I see! My bad!

2023-07-14 05:23 UTC, merged