Change `char`->`free` to `auto_char char` for autocleanup
profanity-im/profanity pull request #1863
Opened 2023-07-04 16:31 UTC by H3rnand3zzz

See commit messages. First part of big cleanup (#1858 ).

# I ran valgrind when using my new feature
No

- [x] Manual review
- [ ] Run Valgrind

2023-07-05 09:29 UTC, jubalh commented
Please adjust commit message accordingly. I think this description is much more descriptive of what you are trying to accomplish `Move from `char` to `auto_char` to automatically free it`.

2023-07-05 09:30 UTC, jubalh requested changes
Now you started to split the commits into several PRs, which is okay.
But inside the commit you still do several unrelated things.
Please change that and see https://github.com/profanity-im/profanity/pull/1858#issuecomment-1621373770

2023-07-05 14:19 UTC, H3rnand3zzz commented
Maybe I will do it later, right now I am unable to.

2023-07-05 16:43 UTC, jubalh commented
> Maybe I will do it later, right now I am unable to.

I made the changes as discussed via PM.

2023-07-06 05:45 UTC, jubalh requested changes
you remove _is_correct_plugin_extension etc. probably mistake during your rebase on master

2023-07-10 05:35 UTC, jubalh requested changes
Please see comments.
And osx CI:
```
src/command/cmd_funcs.c:135:1: error: function '_download_install_plugin' has internal linkage but is not defined [-Werror,-Wundefined-internal]
_download_install_plugin(ProfWin* window, gchar* url, gchar* path);
^
src/command/cmd_funcs.c:7055:9: note: used here
        _download_install_plugin(window, args[1], NULL);
        ^
```

2023-07-10 05:35 UTC, jubalh commented on src/command/cmd_funcs.c
> + * @return Returns TRUE if profanity is to continue, FALSE otherwise.
I don't see what advantage this comment has over the one we already had.
It's just more lengthy.

2023-07-10 05:35 UTC, jubalh commented on src/command/cmd_funcs.c
> -static gboolean
Why is `_download_install_plugin()` deleted?

2023-07-10 05:35 UTC, jubalh commented on src/xmpp/connection.c
> +    ;
`;`

2023-07-11 05:24 UTC, jubalh commented on src/command/cmd_funcs.c
> -static gboolean
@H3rnand3zzz I edited your commit and added the function back

2023-07-11 05:24 UTC, jubalh commented on src/xmpp/connection.c
> +    ;
@H3rnand3zzz I removed that now

2023-07-11 05:25 UTC, jubalh commented
@H3rnand3zzz can you please review this PR? I 2 above mentioned edits.

2023-07-11 08:54 UTC, H3rnand3zzz commented
> @H3rnand3zzz can you please review this PR? I 2 above mentioned edits.

those are correct changes, thanks

2023-07-11 12:57 UTC, jubalh commented on src/command/cmd_funcs.c
> + * @return Returns TRUE if profanity is to continue, FALSE otherwise.
Re doxygen please see https://github.com/profanity-im/profanity/issues/1859

2023-07-11 12:57 UTC, jubalh commented on src/database.c
>  out:
Would be good to test this before we can merge

2023-07-11 12:57 UTC, jubalh commented on src/otr/otr.c
> +        free(message_send_chat_otr(barejid, otr_query_message, FALSE, NULL));
lets leave it for now to get on with this

2023-07-12 11:51 UTC, jubalh approved these changes
Should be ok now

2023-07-12 11:51 UTC, merged

2023-07-12 11:52 UTC, jubalh commented
Thanks for your effort!