Move related commands as subcommands into /privacy
profanity-im/profanity pull request #1870
Opened 2023-07-25 09:25 UTC by jubalh

Fix https://github.com/profanity-im/profanity/issues/1836

2023-07-25 18:16 UTC, jubalh commented
@H3rnand3zzz could you review?

2023-07-25 19:04 UTC, jubalh commented
I added some more changes. Will have to self test myself tomorrow :)

2023-07-26 14:41 UTC, H3rnand3zzz requested changes

2023-07-26 14:41 UTC, H3rnand3zzz commented on src/ui/console.c
> +            cons_show("Client name (/account set <account> clientid)  : %s", account->client);
Hopefully, the spacing can be fixed.

2023-07-26 18:44 UTC, jubalh commented on src/ui/console.c
> +            cons_show("Client name (/account set <account> clientid)  : %s", account->client);
should be done

2023-07-27 08:23 UTC, H3rnand3zzz approved these changes

2023-07-27 08:27 UTC, merged