Refactor some internals
profanity-im/profanity pull request #1884
Opened 2023-08-30 06:56 UTC by sjaeckel

Please check commit messages for details.

2023-08-30 07:11 UTC, jubalh requested changes
```
 src/xmpp/connection.c:1115:27: error: unused variable 'g_accounts_data' [-Werror,-Wunused-variable]
        auto_gchar gchar* g_accounts_data = g_key_file_to_data(keyfile.keyfile, &g_data_size, NULL);
```

2023-09-01 08:30 UTC, H3rnand3zzz commented on src/common.c
> +        return NULL;
I am not sure that it's a very good handling of malloc, since it will make "silent" malfunction. We can discuss it more in MUC.

2023-09-04 07:34 UTC, jubalh commented on src/ui/window.c
> +            if (show_titlebar_jid)
this one had me thinking for a while :D

2023-09-04 07:34 UTC, jubalh approved these changes

2023-09-04 07:34 UTC, merged