Handle alt+enter as newline char
profanity-im/profanity pull request #1927
Opened 2023-11-11 19:08 UTC by H3rnand3zzz

See commit message.

### How to test functionality
Write a message and use alt+enter during writing to put a new character symbol there. Plain "Enter" for sending message/command should work as well as before.

### Why alt+enter?
Well, you see, shift+enter and ctrl+enter aren't that bindable, as you can see by using `showkey --ascii` command. Though shift/ctrl variants might be more preferable since they are used in some popular applications, we just can't bind on them using GNU Readline, while alt+enter does the work as well. 

I will be glad if someone can improve the solution to take keybinding from preference and allow custom settings for ctrl+enter, shift+enter etc. Though even current solution will suffice in terms of functionality and you can get used to it quite quickly.

2023-11-13 08:36 UTC, jubalh requested changes
Should be mentioned in the keybinding section in `docs/profanity.1` as well.

2023-11-13 08:40 UTC, H3rnand3zzz commented
> Should be mentioned in the keybinding section in `docs/profanity.1` as well.

Done, thx for quick review :)

2023-11-13 08:42 UTC, jubalh approved these changes

2023-11-13 08:46 UTC, merged

2025-09-09 12:18 UTC, mrusme commented
Sorry to resurface this PR, but either this feature broke with 0.15.0 or I have _something_ set in my Zsh environment that breaks this feature, as I cannot seem to be able to insert line breaks into a message by pressing Alt+Enter.

Could anyone confirm that this feature is still functional please?

2025-09-09 12:54 UTC, sjaeckel commented
> Could anyone confirm that this feature is still functional please?

works for me!

Are you sure you have profanity in focus in the window?

2025-09-09 13:40 UTC, mrusme commented
> works for me!

Thank you!

> Are you sure you have profanity in focus in the window?

Yup, it's in focus. Pressing Alt+Enter sends the message. Hm, very strange.

2025-09-09 13:44 UTC, jubalh commented
Maybe check your .inputrc / readline config

2025-09-09 13:48 UTC, mrusme commented
My `~/.config/profanity/inputrc` only specifies the following:

```
$if profanity
  "\C-h": prof_win_prev
  "\C-l": prof_win_next
$endif
```

2025-09-09 13:50 UTC, jubalh commented
Did this feature work for you before? If yes, did you switch to another terminal since then? Does your WM/Terminal maybe grab any of the keys?

2025-09-09 13:53 UTC, mrusme commented
The global `/etc/inputrc` on the other hand defaults to this configuration:

```
# /etc/inputrc: initialization file for readline
#
# For more information on how this file works, please see the
# INITIALIZATION FILE section of the readline(3) man page
#
# Quick dirty little note:
#  To get the key sequence for binding, you can abuse bash.
#  While running bash, hit CTRL+V, and then type the key sequence.
#  So, typing 'ALT + left arrow' in Konsole gets you back:
#    ^[[1;3D
#  The readline entry to make this skip back a word will then be:
#    "\e[1;3D" backward-word
#
# Customization note:
#  You don't need to put all your changes in this file.  You can create
#  ~/.inputrc which starts off with the line:
#    $include /etc/inputrc
#  Then put all your own stuff after that.
#

# do not bell on tab-completion
#set bell-style none

set meta-flag on
set input-meta on
set convert-meta off
set output-meta on

# Completed names which are symbolic links to
# directories have a slash appended.
set mark-symlinked-directories on

$if mode=emacs

# for linux console and RH/Debian xterm
# allow the use of the Home/End keys
"\e[1~": beginning-of-line
"\e[4~": end-of-line
# map "page up" and "page down" to search history based on current cmdline
"\e[5~": history-search-backward
"\e[6~": history-search-forward
# allow the use of the Delete/Insert keys
"\e[3~": delete-char
"\e[2~": quoted-insert

# gnome / others (escape + arrow key)
"\e[5C": forward-word
"\e[5D": backward-word
# konsole / xterm / rxvt (escape + arrow key)
"\e\e[C": forward-word
"\e\e[D": backward-word
# gnome / konsole / others (control + arrow key)
"\e[1;5C": forward-word
"\e[1;5D": backward-word
# aterm / eterm (control + arrow key)
"\eOc": forward-word
"\eOd": backward-word

# konsole (alt + arrow key)
"\e[1;3C": forward-word
"\e[1;3D": backward-word

# Chromebooks remap alt + backspace so provide alternative (alt + k)
"\ek": backward-kill-word

$if term=rxvt
"\e[8~": end-of-line
$endif

# for non RH/Debian xterm, can't hurt for RH/Debian xterm
"\eOH": beginning-of-line
"\eOF": end-of-line

# for freebsd console
"\e[H": beginning-of-line
"\e[F": end-of-line
$endif

# fix Home and End for German users
"\e[7~": beginning-of-line
"\e[8~": end-of-line
```

2025-09-09 13:54 UTC, mrusme commented
> Did this feature work for you before? If yes, did you switch to another terminal since then? Does your WM/Terminal maybe grab any of the keys?

Frankly I had never tested it before. :) It's only when I tried to quote a message (`>`+tab) that I wanted to enter a new line to append my comment, which is when I noticed it not working.

2025-09-09 17:31 UTC, jubalh commented
I'm not sure why it doesn't work for you.
Did you try to empty the global inputrc just for testing purposes?

As an alternative you could use ALT+c to open the editor and edit the multiline message there.

2025-09-10 11:47 UTC, mrusme commented
@jubalh thank you, Alt+c works perfectly fine! As for emptying the global inputrc: I just tried it while being logged in and it didn't make a difference. I will try again, log out and log back in, just to make sure.