Implement substring autocompletion for /msg
profanity-im/profanity pull request #1985
Opened 2024-06-20 14:25 UTC by jubalh

People with huge contact lists most likely happen to have contacts starting with popular names more often. They can use /msg Arthur to find the correct person.

But if they have 50 Arthurs it will take a while. Using the surname might be faster. So a substring search of /msg Clarke<tab> will be faster.

Fix https://github.com/profanity-im/profanity/issues/1984

2024-06-24 08:19 UTC, jubalh commented
roster_contact_autocomplete() is used for:
* /msg
* /info
* /roster remvoe
* /roster group add
* /roster group remove
* /otr policy
* /pgp start
* /pgp sendpub
* /ox start
* /omemo start
* /omemo fingerprint
* /omemo trust
* /omemo untrust
* /win
* /invite send
* /status get
* /vcard get
* /vcard photo open
* /vcard photo save

@mdosch @weiss @sjaeckel 
What are your opinions? Should we generally make `roster_contact_autocomplete()` autocomplete substrings? Or should we do it as proposed in this PR. That we have two functions, one for the exact prefix and the other for substring.
If we do the latter, do we want it for more functions than `/msg`?

2024-06-26 17:33 UTC, mdosch commented
If you have a lot of Arthurs the issue of having to tab a lot till you find the right Arthur can happen with any command, so I think we should allow the substring search everywhere. But for the ordering I'd like to rank hits starting with the search term higher.

E.g. if you have "Arthur Anchor", Arthur Boyle", "Arthur Clarke", "Arthur Dent" and "Clark Kent" `/msg Clark<tab>` should show "Clark Kent" first and then "Arthur Clarke".

2025-04-16 10:09 UTC, sjaeckel requested changes
LGTM

and
1. I like the idea of @mdosch 
2. that's one of the cases where I think tests would make sense :)

2025-04-16 10:09 UTC, sjaeckel commented on src/tools/autocomplete.c
>  gchar*
`static`

2026-03-26 23:01 UTC, jubalh commented
I dont remember what exactly, but something was wrong with this PR. So probably will create a new one for the issue.

2026-03-26 23:01 UTC, closed without merging